dist: bionic
language: minimal
services:
  - docker
env:
  global:
    - USERNAME_TAG=obscuritylabs
    - ASE_BASEIMAGE_TAG=ase

jobs:
  include:
    - script: cd ase_docker && docker build --squash --compress -t $USERNAME_TAG/$ASE_BASEIMAGE_TAG:latest .
    - script: cd ase_docker/searchsploit && docker build --squash --compress -t $USERNAME_TAG/$ASE_BASEIMAGE_TAG:latest .