dist: bionic
language: minimal
services:
  - docker
env:
  global:
    - USERNAME_TAG=obscuritylabs
    - ASE_BASEIMAGE_TAG=ase

before_install:
  - sudo apt-get install build-essential

install:
  - cd ase_docker && docker-compose build --parallel